# Generated by Django 5.0.4 on 2024-05-17 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_procedimento', models.CharField(max_length=50)),
                ('valor_procedimento', models.IntegerField()),
            ],
            options={
                'ordering': ['nome_procedimento'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateField()),
                ('nome_paciente', models.CharField(max_length=55, verbose_name='Paciente')),
                ('idade', models.CharField(max_length=5)),
                ('telefone', models.CharField(max_length=14)),
                ('edereco', models.CharField(max_length=100)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('inicio_atendimento', models.TimeField()),
                ('valor_consulta', models.IntegerField()),
                ('fim_atendimento', models.DateTimeField(blank=True, null=True)),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('nome_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.paciente')),
                ('tipo_consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamentos.procedimento')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
